name: Autodeploy
on:
  push:
    branches:
      - main
jobs:
  Pull-from-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2.3.1

        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
          if_key_exists: ignore

      - name: Pull via ssh
        uses: nerd4ever/ssh-action@0.1.0
        with:
          command:
            cd /var/www/w8t/bullTranch && git pull origin main && npm run build || exit
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY}}
